### ISSUE TITLE
[Docs] Quick Start index.js code has a mistake

### ISSUE THREAD

**Issue by jonesnc** [Canner/gqlify#30]
**Describe the bug**
The code for the `index.js` file on the [Quick Start](url
https://www.gqlify.com/docs/quick-start#setup-gqlify) docs page has a mistake.

```
// Read datamodel
const sdl = readFileSync(__dirname + '/demo.graphql', { encoding: 'utf8' });
```

The `readFileSync` function was not imported from `fs`.

**Suggested Fix**

To fix, add `const { readFileSync } = require(‘fs’);` to the imports for the `index.js` file.

**Comment by wwwy3y3** [comment]
Thanks for the report!

**Comment by chilijung** [comment]
Fixed thanks!
