### ISSUE TITLE
I can't seem to find the docs to contribute

### ISSUE THREAD

**Issue by jthegedus** [Canner/gqlify#42]
**Is your feature request related to a problem? Please describe.**
I can't find the gqlify docs

**Describe the solution you'd like**
I would like to contribute to the docs but cannot find the source

**Describe alternatives you've considered**
Checked in the Canner org repos

**Comment by wwwy3y3** [comment]
Hi @jthegedus 

Glad to hear your willingness to contribute.

We just open-source our document here (https://github.com/Canner/docs.gqlify.com).

**Comment by jthegedus** [comment]
Thanks
