### ISSUE TITLE
use @gqlify/firestore without cert & dbUrl

### ISSUE THREAD

**Issue by jthegedus** [Canner/gqlify#43]
**Is your feature request related to a problem? Please describe.**
I am using GQLify in a Firebase Cloud Function and would like to avoid uploading and storing my service account json file.

**Describe the solution you'd like**
When in a Google secure environment, like Cloud Functions, you are not required to provide `cert: admin.ServiceAccount` or `dbUrl: string` to `admin.initializeApp()`.

I would like to change the constructor of the firestore plugin to check for 
`process.env.FIREBASE_CONFIG` to see if it's in a Cloud Function environment and call `initializeApp()` without the params, otherwise, continue as it does now.

```js
  constructor(cert: admin.ServiceAccount, dbUrl: string, path: string) {
    this.db = isEmpty(admin.apps)
      ? admin.initializeApp({
        credential: admin.credential.cert(cert),
        databaseURL: dbUrl,
      }).firestore()
      : admin.app().firestore();
    this.path = path;
  }
```

would become something like this

```js
  constructor(cert: admin.ServiceAccount, dbUrl: string, path: string) {
	this.db = isEmpty(admin.apps)
	  ? process.env.FIREBASE_CONFIG
	    ? admin.initializeApp().firestore()
	    : admin
	        .initializeApp({
	          credential: admin.credential.cert(cert),
	          databaseURL: dbUrl
	        })
	        .firestore()
	  : admin.app().firestore();
    this.path = path;
  }
```

and I when using inside a Cloud Function it could be called like so:

```js
const gqlify = new Gqlify({
    sdl,
    dataSources: {
      firestore: args => new FirestoreDataSource(null, null, args.key),
    },
    skipPrint: true,
  });
```
using `null` is not ideal, but it's backwards compatible.

**Additional Information**

The information about env vars, see here - https://firebase.google.com/docs/functions/config-env#automatically_populated_environment_variables

About initializing the SDK using the Google Application Default Credentials, see here - https://firebase.google.com/docs/admin/setup#initialize_the_sdk

most importantly:

> The Admin SDKs can alternatively be authenticated with a different credential type. For example, if you are running your code within Google Cloud Platform, you can make use of Google Application Default Credentials to have the Admin SDKs themselves fetch a service account on your behalf:

> The SDK can also be initialized with no parameters. In this case, the SDK uses Google Application Default Credentials...

I can create a PR for this tomorrow myself, was just curious if there was any other input for a better way to achieve the same outcome.

Thanks

**Comment by wwwy3y3** [comment]
hi @jthegedus 

Thanks for the solid points and detailed information!

Base on your information, it comes with all different forms in terms of `initializeApp` argument.

Thus, I decided to let developers choose what to pass in `intializeApp`.

Starting from `v2.0.0`, you may use the following api:

### With serviceAccount
```ts
const databaseURL = `https://${serviceAccount.project_id}.firebaseio.com`;
const gqlify = new Gqlify({
    sdl,
    dataSources: {
      firestore: args => new FirestoreDataSource({
          // config will be passed to initializeApp directly
          config: {
            credential: admin.credential.cert(serviceAccount),
            databaseURL,
          },
          path: args.key,
      }),
    },
  });
```

### In cloud function
```ts
const gqlify = new Gqlify({
    sdl,
    dataSources: {
      firestore: args => new FirestoreDataSource({
          // just remove `config` argument, nothing will be passed to initializeApp
          path: args.key,
      }),
    },
  });
```

**Comment by jthegedus** [comment]
A much more flexible API, thanks a bunch Will. Works brilliantly!
