### ISSUE TITLE
Give it a new future

### ISSUE THREAD

**Issue by cerebrowang** [Canner/gqlify#51]

**Comment by singerswang** [comment]
This is my profile https://www.linkedin.com/in/singerswang/
Powered by Huawei, Inspur and Haier.

**Comment by singerswang** [comment]
If you think ok, the domain “gqlbase.com" own you in 0 price.
And transfer your account.
Hosting in name.com

**Comment by singerswang** [comment]
Contact with GitHub or my email singerswang {at} x.ly

**Comment by singerswang** [comment]
Annual Renewal: ¥87.34

**Comment by singerswang** [comment]
@abz53378 @wwwy3y3 @chilijung

**Comment by cerebrowang** [comment]
Rename it to gqlbase.com.
Relocation it, before firebase into Chinese market (with it, all is its.)
A database Power by GraphQL.
Power by GraphQL, we database everything.
Inspired by your cms30.
This is my profile https://www.linkedin.com/in/singerswang/
Powered by Huawei, Inspur and Haier.
If it is ok, the domain “gqlbase.com" own you in $0 price.
We can transfer in your account.
Hosting in name.com.
transferwith$0pricein30days@gqlbase.com
I only want a nominal (仅名义上的) co-founder. In charge of financing in STO, but No promised.
所占公司股份 1%.我完全不参与管理。这 1% 为普通股。
你们团队入眼理由
1.已实作，不吹牛。
2.懂中文，好沟通。
还是那句话：伟大的卓越，永远诞生在犄角旮旯！你们的野心有多大，世界的舞台就有多大！
此邀约在30天内有效，若你们不回复，我找下一个团队，直到找到了为止，我很欣赏你们的作品，但我无法一直无限期等待下去，此邀约在30天自然日内有效。
要么成为商业上的伙伴 singingwang@sto.org ，要么成为市场上的竞争者，选择权在你们。我们等你们作出自己的选择或你们的Offer。谢谢。
